[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit-app"
version = "0.1.0"
description = "Chinese Medicine Formula Analysis System"
requires-python = ">=3.9"
